# Generated by Django 3.2.13 on 2023-10-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
